### ISSUE TITLE
Demo does not seem to work

### ISSUE THREAD

**Issue by oliverpool** [tus/tus.io#104]
Your project looks really nice.

I tried the [online demo](https://tus.io/demo.html), but nothing happened (on Chromium and on Firefox - on arch linux).

Looking at the Chromium console, I found this:

```
upload-demo.js?c221:15
Uncaught ReferenceError: tus is not defined
    at HTMLDocument.eval (eval at <anonymous> (https://tus.io/assets/build/app.js:162:2), <anonymous>:15:8)
    at fire (eval at <anonymous> (https://tus.io/assets/build/app.js:66:2), <anonymous>:3182:31)
    at Object.fireWith [as resolveWith] (eval at <anonymous> (https://tus.io/assets/build/app.js:66:2), <anonymous>:3312:7)
    at Function.ready (eval at <anonymous> (https://tus.io/assets/build/app.js:66:2), <anonymous>:3531:13)
    at HTMLDocument.completed (eval at <anonymous> (https://tus.io/assets/build/app.js:66:2), <anonymous>:3547:9)
```

Any idea what is happening?

**Comment by Acconut** [comment]
Thank you for reporting. We just changed to tool for building the tus.io website the days ago and I assume that this could be the root cause. @kvz, do you have an idea?

**Comment by kvz** [comment]
Thanks @oliverpool I think https://github.com/tus/tus.io/commit/09c7d30a9518b72a9a67fb0b790caad69a8aef0d should fix it. We switched to Webpack and by default have no global scope to dump objects in like we did. Can you refresh and confirm it's working for you again?

**Comment by Acconut** [comment]
Works again. Thank you, Kevin!

**Comment by oliverpool** [comment]
Works perfectly fine.

Tus looks really good, I'll give it a try for my next project!

**Comment by kvz** [comment]
Sounds excellent! Let us know how it goes!
