### ISSUE TITLE
Errors when building assets

### ISSUE THREAD

**Issue by kvz** [tus/tus.io#26]
Please see the full output here

```bash
$ make build-assets
--> Building assets..

> tus-io@0.0.1 build /Users/kvz/code/tus.io
> run-scripts css js

util.print: Use console.log instead

> tus-io@0.0.1 css /Users/kvz/code/tus.io
> run-scripts css:less css:prefix css:minify


> tus-io@0.0.1 css:less /Users/kvz/code/tus.io
> lessc _assets/app.less > assets/build/app.css


> tus-io@0.0.1 css:prefix /Users/kvz/code/tus.io
> autoprefixer assets/build/app.css


> tus-io@0.0.1 css:minify /Users/kvz/code/tus.io
> cleancss -o ./assets/build/app.css ./assets/build/app.css

util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead

> tus-io@0.0.1 js /Users/kvz/code/tus.io
> run-scripts js:hint js:concat js:minify


> tus-io@0.0.1 js:hint /Users/kvz/code/tus.io
> jshint $(find ./_assets/js -name "*.js")


> tus-io@0.0.1 js:concat /Users/kvz/code/tus.io
> concat-from-list _assets/app.cson assets/build/app.js

/Users/kvz/code/tus.io/node_modules/concat-from-list/index.js:65
                files.forEach(function (file) {
                      ^
TypeError: undefined is not a function
  at [object Object].run (/Users/kvz/code/tus.io/node_modules/concat-from-list/index.js:65:9)
  at Object.<anonymous> (/Users/kvz/code/tus.io/node_modules/concat-from-list/bin/concat-from-list:19:12)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3


npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "js:concat"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! tus-io@0.0.1 js:concat: `concat-from-list _assets/app.cson assets/build/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tus-io@0.0.1 js:concat script 'concat-from-list _assets/app.cson assets/build/app.js'.
npm ERR! This is most likely a problem with the tus-io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concat-from-list _assets/app.cson assets/build/app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls tus-io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kvz/code/tus.io/npm-debug.log
exec error: Error: Command failed: /bin/sh -c npm run js:concat
/Users/kvz/code/tus.io/node_modules/concat-from-list/index.js:65
                files.forEach(function (file) {
                      ^
TypeError: undefined is not a function
  at [object Object].run (/Users/kvz/code/tus.io/node_modules/concat-from-list/index.js:65:9)
  at Object.<anonymous> (/Users/kvz/code/tus.io/node_modules/concat-from-list/bin/concat-from-list:19:12)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3


npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "js:concat"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! tus-io@0.0.1 js:concat: `concat-from-list _assets/app.cson assets/build/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tus-io@0.0.1 js:concat script 'concat-from-list _assets/app.cson assets/build/app.js'.
npm ERR! This is most likely a problem with the tus-io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concat-from-list _assets/app.cson assets/build/app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls tus-io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kvz/code/tus.io/npm-debug.log


> tus-io@0.0.1 js:minify /Users/kvz/code/tus.io
> uglifyjs assets/build/app.js -o assets/build/app.js

util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
util.print: Use console.log instead
```

Just for me or for everyone? I'm using 

```bash
$ node -v
v0.12.4
```

on OSX.

/cc @fahad19

**Comment by Acconut** [comment]
Works for me on Ubuntu using node v0.10.

**Comment by kvz** [comment]
One error resolved. One error remains from [concat-from-list](https://www.npmjs.com/package/concat-from-list) @fahad19:

I added some debug statements around line 39

```bash
			list = cson.parseFileSync(this.listPath);
			console.log(cson);
			console.log(cson.parseFileSync);
			console.log(list);
			console.log(this.listPath);
```

```bash
$ ./node_modules/.bin/concat-from-list _assets/app.cson assets/build/app.js
{ parseFile: [Function],
  parseFileSync: [Function],
  parse: [Function],
  parseSync: [Function],
  stringify: [Function],
  stringifySync: [Function] }
[Function]
[TypeError: undefined is not a function]
_assets/app.cson
/Users/kvz/code/tus.io/node_modules/concat-from-list/index.js:69
		files.forEach(function (file) {
		      ^
TypeError: undefined is not a function
  at [object Object].run (/Users/kvz/code/tus.io/node_modules/concat-from-list/index.js:69:9)
  at Object.<anonymous> (/Users/kvz/code/tus.io/node_modules/concat-from-list/bin/concat-from-list:19:12)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by fahad19** [comment]
thanks for the work around @kvz!

@marius, @kvz: please CC me on any bug on Slack so I don't miss it, since my GitHub is full of work notifications.

**Comment by kvz** [comment]
NP! Ok thanks, will do!
